### ISSUE TITLE
[frontend-app-communications] Localization issues

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-communications#148]
### Description

(This is being tracked via https://github.com/openedx/wg-translations/issues/16.)

There have been independent reports of problems with localization related to this MFE, which has been made part of the official Tutor release as of Palm.  The main objective here is to find out what the problems are, and then to coordinate fixes.

#### Report 1

This was first noted [on Slack](https://openedx.slack.com/archives/C037XDB9KN1/p1691157409234449) by @sambapete on 2023-08-04.  Thread summary:

* There seems to be no Transifex resource for the MFE
* There are no translations in https://github.com/openedx/frontend-app-communications/tree/open-release/palm.1/src/i18n/messages
* On 2023-03-24 [a PR was merged](https://github.com/openedx/frontend-app-communications/pull/119) that upgraded the repo's Transifex support to v3.  It is equivalent to others such as [this other one](https://github.com/openedx/frontend-app-learning/pull/837) in frontend-app-learning, the latter of which seems to be working properly.
* It seems these translations are still handled by Jenkins jobs, over which the community has no visibility

#### Report 2

[An issue was opened in this repository](https://github.com/openedx/frontend-app-communications/issues/146) noting that there doesn't seem to be a Transifex resource for frontend-app-communications.

### Solution space

In [a separate thread](https://openedx.slack.com/archives/C037XDB9KN1/p1693932538894329) started to coordinate fixing this and other outstanding i18n issues, it was hypothesized that the Jenkins bot responsible for exporting strings to Transifex was not properly set up.  Evidence: no [commits by `edx-transifex-bot` to `src/i18n`](https://github.com/openedx/frontend-app-communications/commits/master/src/i18n).

Assuming this is the only problem, a solution was proposed where instead of trying to hunt down the maintainers of the bot - a recurring issue - frontend-app-communications should be one of the first repositories to work exclusively with https://github.com/openedx/openedx-atlas (as introduced via OEP-58).

The potential downside is that for Quince, and until all repositories are ported to openedx-atlas, translators would have to work with two Transifex projects.  However:

* At least one active Transifex user (@sambapete) noted that that would be acceptable.
* @OmarIthawi notes that it might be possible to synchronize Transifex projects so translators need not know about the separate projects

#### Standing questions

* The cut for Quince.master is just a month away.  Will this be ready in time?
* How will the proposed solution be handled in Tutor, as per https://github.com/overhangio/tutor-mfe#adding-custom-translations-to-your-mfes?

### Additional references

* https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html
* https://github.com/openedx/edx-platform/pull/32994
* https://github.com/openedx/openedx-translations/pull/569

```[tasklist]
### PRs
- [ ] https://github.com/overhangio/tutor-mfe/pull/149
```

**Comment by OmarIthawi** [comment]
@arbrandes Thanks for bringing this up.

@sambapete do you have access to the following Transifex resource:

 - https://app.transifex.com/open-edx/openedx-translations/translations-frontend-app-communications-src-i18n-transifex-input-json--main/

You may add some translations, it's a relatively small resource with under a hundred entry.

> @OmarIthawi notes that it might be possible to synchronize Transifex projects so translators need not know about the separate projects

Not exactly. Synchronization will be done, but as part of a cut-off i.e. deprecate old resources while moving the translations to new resources with _preserved review status_.

This is to address concerns by few community members that Review status is very valuable translation workflow data and saves a lot of time.

**Comment by sambapete** [comment]
@OmarIthawi I don't have access to this new resource or project.

**Comment by OmarIthawi** [comment]
I'll add you @sambapete today.

**Comment by arbrandes** [comment]
Status update: the required feature was added to tutor-mfe nightly, which will automatically land in Quince before release.

**Comment by arbrandes** [comment]
This should've been closed ages ago.
