### ISSUE TITLE
upgrade footer, header, and platform deps to allow paragon upgrades

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-app-communications#188]
the current state of peer dependencies prevents `paragon` upgrades due to the `@edx` vs `@openedx` scope difference

once the following PRs are merged we should update these dependencies to allow `paragon` upgrades using the `@openedx` scope
* https://github.com/openedx/frontend-component-footer/pull/394
* https://github.com/openedx/frontend-component-header/pull/456
* https://github.com/openedx/frontend-platform/pull/636

**Comment by arbrandes** [comment]
I figure we can close this one, right?
